@baseUrl = http://localhost:3000


# Health check
# @name healthCheck
GET {{baseUrl}}/health
###
GET {{baseUrl}}/api
###
POST {{baseUrl}}/api/auth/sign-up
Content-Type: application/x-www-form-urlencoded

name=Jhonne
&email=jonee4339@hotmail.com
&password=123123